[package]
name = "sha256-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
hex = "0.4.3"
sha256 = "1.3.0"

[[bench]]
name = "my_benchmark"
harness = false
